### ISSUE TITLE
Use forked version of express-react-views since temporarily during switch to (real) react + redux

### ISSUE THREAD

**Issue by jeremyosborne** [jeremyosborne/easy-on-the-eyes#18]
Oh the joys of the react toolchain. After losing a couple of hours this morning, I feel I need to switch over to a more standard react app vs. this frankenstein experiment.

The culprit turned out to be `express-react-views` and in particular this block of code in the `./index.js`:

```javascript
        // Remove all files from the module cache that are in the view folder.
        Object.keys(require.cache).forEach(function(module) {
          if (moduleDetectRegEx.test(require.cache[module].filename)) {
            delete require.cache[module];
          }
        });
```

The stack trace is:

```
info: Listening on port 3000
    GET / 500 1466.204 ms - 1154
    TypeError: Cannot read property 'filename' of undefined
        at /Users/josborne/src/easy-on-the-eyes/node_modules/express-react-views/index.js:61:59
        at Array.forEach (native)
        at View.renderFile [as engine] (/Users/josborne/src/easy-on-the-eyes/node_modules/express-react-views/index.js:60:36)
        at View.render (/Users/josborne/src/easy-on-the-eyes/node_modules/express/lib/view.js:126:8)
        at tryRender (/Users/josborne/src/easy-on-the-eyes/node_modules/express/lib/application.js:639:10)
        at EventEmitter.render (/Users/josborne/src/easy-on-the-eyes/node_modules/express/lib/application.js:591:3)
        at ServerResponse.render (/Users/josborne/src/easy-on-the-eyes/node_modules/express/lib/response.js:960:7)
        at /Users/josborne/src/easy-on-the-eyes/server/app/index.js:55:7
        at Layer.handle [as handle_request] (/Users/josborne/src/easy-on-the-eyes/node_modules/express/lib/router/layer.js:95:5)
        at next (/Users/josborne/src/easy-on-the-eyes/node_modules/express/lib/router/route.js:131:13)
```

**Comment by jeremyosborne** [comment]
Tried switching versions of node, appears to be a problem with the cache, or at least the cache references on my system somehow becoming undefined.

**Comment by jeremyosborne** [comment]
For now, immediate solution will be to fork that module and use it to give me time to dump the module.
